#index:
#    path: /
#    controller: App\Controller\DefaultController::index
appFrontend:
    resource: "@AppFrontendBundle/Resources/config/routes.yaml"

appBackend:
    resource: "@AppBackendBundle/Resources/config/routes.yaml"

